SweetSavory/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SweetSavory.Models
{
    public class Treat
    {
        public int TreatId { get; set; }
        [Required(ErrorMessage = "A name is required.")]
        public string Name { get; set;}
        [Required(ErrorMessage = "A price must be set.")]
        public int Price { get; set;}
        [Required(ErrorMessage = "A description is required.")]
        public string Description { get; set;}
        public List<TreatFlavor> JoinTable { get;}
    }
}

SweetSavory/Controllers/FlavorsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using SweetSavory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;

namespace SweetSavory.Controllers
{
    public class FlavorsController : Controller
    {
        private readonly SweetSavoryContext _db;
        public FlavorsController(SweetSavoryContext db)
        {
            _db = db;
        }
        
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Title = "Add Flavor";
            return View();
        }
        [HttpPost]
        public ActionResult Create(Flavor flavor)
        {
            if (!ModelState.IsValid)
            {
                return View(flavor);
            }
            else
            {
                _db.Flavors.Add(flavor);
                _db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult Details (int id)
        {
        Flavor flavorModel = _db.Flavors
                    .Include(entry => entry.JoinTable)
                    .ThenInclude(entry => entry.Treat)
                    .FirstOrDefault(entry => entry.FlavorId == id);
        ViewBag.Title = flavorModel.Name;
        ViewBag.Treatlist = _db.Treats.ToList();
        ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
        return View(flavorModel);
        }

        [HttpPost]
        public ActionResult AddTreat(Flavor flavor, int treatId)
        {
            #nullable enable
            TreatFlavor? joinEntry = _db.TreatFlavors.FirstOrDefault(entry  =>(entry.TreatId == treatId && entry.FlavorId == flavor.FlavorId));
            #nullable disable
            if (joinEntry == null && treatId != 0)
            {
                _db.TreatFlavors.Add(new TreatFlavor() { TreatId = treatId, FlavorId = flavor.FlavorId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new {id = flavor.FlavorId});
        }

        [HttpPost]
        public ActionResult DeleteJoin(int joinId)
        {
            TreatFlavor joinEntry = _db.TreatFlavors.FirstOrDefault(joinEntry => joinEntry.TreatFlavorId == joinId);
            _db.TreatFlavors.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Details", new {id = joinEntry.FlavorId});
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            ViewBag.Title = "Edit Flavor";
            Flavor flavorModel = _db.Flavors.FirstOrDefault(entry => entry.FlavorId == id);
            return View(flavorModel);
        }

        [HttpPost]
        public ActionResult Edit(Flavor flavor)
        {
            if (!ModelState.IsValid)
            {
                return View(flavor);
            }
            else
            {
            _db.Flavors.Update(flavor);
            _db.SaveChanges();
            return RedirectToAction("Details", new {id = flavor.FlavorId});
            }
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
        ViewBag.Title = "Delete Flavor";
        Flavor flavorModel = _db.Flavors.FirstOrDefault(entry => entry.FlavorId == id);
        return View(flavorModel);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            Flavor targetFlavor = _db.Flavors.FirstOrDefault(entry => entry.FlavorId == id);
            _db.Flavors.Remove(targetFlavor);
            _db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

    }


}

SweetSavory/Controllers/TreatsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using SweetSavory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;


namespace SweetSavory.Controllers
{
    public class TreatsController : Controller
    {
        private readonly SweetSavoryContext _db;
        public TreatsController(SweetSavoryContext db)
        {
            _db = db;
        }
        
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Title = "Add Treat";
            return View();
        }
        [HttpPost]
        public ActionResult Create(Treat treat)
        {
            if (!ModelState.IsValid)
            {
                return View(treat);
            }
            else
            {
                _db.Treats.Add(treat);
                _db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult Details(int id)
        {
            Treat treatModel = _db.Treats
                        .Include(entry => entry.JoinTable)
                        .ThenInclude(entry => entry.Flavor)
                        .FirstOrDefault(entry => entry.TreatId == id);
            ViewBag.Title = treatModel.Name;
            ViewBag.Flavorlist = _db.Flavors.ToList();
            ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
            return View(treatModel);
        }

        [HttpPost]
        public ActionResult AddFlavor(Treat treat, int flavorId)
        {
            #nullable enable
            TreatFlavor? joinEntry = _db.TreatFlavors.FirstOrDefault(entry  =>(entry.TreatId == treat.TreatId && entry.FlavorId == flavorId));
            #nullable disable
            if (joinEntry == null && flavorId != 0)
            {
                _db.TreatFlavors.Add(new TreatFlavor() { TreatId = treat.TreatId, FlavorId = flavorId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new {id = treat.TreatId});
        }

        [HttpPost]
        public ActionResult DeleteJoin(int joinId)
        {
            TreatFlavor joinEntry = _db.TreatFlavors.FirstOrDefault(joinEntry => joinEntry.TreatFlavorId == joinId);
            _db.TreatFlavors.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Details", new {id = joinEntry.TreatId});
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            ViewBag.Title = "Edit Treat";
            Treat treatModel = _db.Treats.FirstOrDefault(entry => entry.TreatId == id);
            return View(treatModel);
        }

        [HttpPost]
        public ActionResult Edit(Treat treat)
        {
            if (!ModelState.IsValid)
            {
                return View(treat);
            }
            else
            {
            _db.Treats.Update(treat);
            _db.SaveChanges();
            return RedirectToAction("Details", new {id = treat.TreatId});
            }
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
        ViewBag.Title = "Delete Treat";
        Treat treatModel = _db.Treats.FirstOrDefault(entry => entry.TreatId == id);
        return View(treatModel);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            Treat targetTreat = _db.Treats.FirstOrDefault(entry => entry.TreatId == id);
            _db.Treats.Remove(targetTreat);
            _db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

    }


}

SweetSavory/Views/Treats/Create.cshtml
@{
    Layout = "_Layout";
}

@model SweetSavory.Models.Treat

<h2>Create a Treat for the Menu</h2>
<hr>

@if(!ViewData.ModelState.IsValid)
{
    @Html.ValidationSummary("Please fix the following error(s) and then resubmit the form:")
}
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <br>
    @Html.LabelFor(model => model.Description)
    <br>
    @Html.TextAreaFor(model => model.Description)
    <br>
    @Html.LabelFor(model => model.Price)
    @Html.TextBoxFor(model => model.Price , new { type = "number", min="1"})
    <input type="submit" value="Add">
}
<hr>

<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>

SweetSavory/Views/Treats/Delete.cshtml
@{
    Layout = "_Layout";
}

@model SweetSavory.Models.Treat

<h2>Delete Treat: @Model.Name</h2>
<hr>


<h3>If you are sure you want to delete this entry, click "Delete". Otherwise, go back.</h3>
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
<hr>
<p>@Html.ActionLink("Back", "Details", new { id = Model.TreatId})</p>

SweetSavory/Views/Treats/Details.cshtml
@{
    Layout ="_Layout";
}

@using SweetSavory.Models
@model SweetSavory.Models.Treat

<h2>@Model.Name</h2>
<hr>
<p>@Model.Description</p>
<h3>Price: $@Model.Price</h3>
<h3>Flavors:</h3>
@if (Model.JoinTable.Count == 0)
{
    <p>There are no flavors that are associated with this treat.</p>
}
@foreach (TreatFlavor entry in Model.JoinTable)
{
    <h4>@Html.ActionLink($"{entry.Flavor.Name}", "Details", "Flavors", new { id = entry.Flavor.FlavorId})</h4>
    @if(User.Identity.IsAuthenticated)
    {
        @using (Html.BeginForm("DeleteJoin", "Treats"))
        {
            @Html.Hidden("joinId", entry.TreatFlavorId)
            <input type="submit" value="Remove">
        }
    }
}
<hr>

@if(User.Identity.IsAuthenticated)
{
    @if(ViewBag.Flavorlist.Count != 0)
    {
        @using (Html.BeginForm("AddFlavor", "Treats"))
        {
            @Html.HiddenFor(model => model.TreatId)
            @Html.Label("Add a Flavor to this treat")
            @Html.DropDownList("FlavorId")
            <input type="submit" value="Save">
        }
    }

<p>@Html.ActionLink("Edit Treat", "Edit", new {id = Model.TreatId})</p>
<p>@Html.ActionLink("Delete Treat", "Delete", new {id = Model.TreatId})</p>
<hr>

}
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>

SweetSavory/Views/Treats/Edit.cshtml
@{
    Layout = "_Layout";
}

@model SweetSavory.Models.Treat

<h2>Edit Treat: @Model.Name</h2>
<hr>

@if(!ViewData.ModelState.IsValid)
{
    @Html.ValidationSummary("Please fix the following error(s) and then resubmit the form:")
}
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TreatId)
    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)
    <br>
    @Html.LabelFor(model => model.Description)
    <br>
    @Html.TextAreaFor(model => model.Description)
    <br>
    @Html.LabelFor(model => model.Price)
    @Html.EditorFor(model => model.Price , new { type = "number", min="1"})
    <input type="submit" value="Update">
}
<hr>

<p>@Html.ActionLink("Back", "Details", new {id = Model.TreatId})</p>